import { Employee, SignalTower, DisasterConfig } from './types';

export const INITIAL_TOWERS: SignalTower[] = [
  {
    id: 'tower-1',
    name: 'Cebu IT Park Lahug Tower',
    carrier: 'Globe',
    lat: 30,
    lng: 34,
    status: 'ONLINE',
    range: 22,
    capacity: 650,
    currentLoad: 41,
  },
  {
    id: 'tower-2',
    name: 'Mactan Airport MCIA Hub',
    carrier: 'Smart',
    lat: 28,
    lng: 78,
    status: 'CONGESTED',
    range: 25,
    capacity: 500,
    currentLoad: 89,
  },
  {
    id: 'tower-3',
    name: 'Cordova CCLEX South Relay',
    carrier: 'DITO',
    lat: 46,
    lng: 73,
    status: 'OFFLINE',
    range: 20,
    capacity: 350,
    currentLoad: 0,
  },
  {
    id: 'tower-4',
    name: 'Mandaue Reclamation Cell Node',
    carrier: 'Smart',
    lat: 22,
    lng: 45,
    status: 'ONLINE',
    range: 26,
    capacity: 450,
    currentLoad: 21,
  },
  {
    id: 'tower-5',
    name: 'Talisay SRP Coastal Array',
    carrier: 'Globe',
    lat: 65,
    lng: 22,
    status: 'CONGESTED',
    range: 24,
    capacity: 400,
    currentLoad: 78,
  }
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'Maria Clarissa Santos',
    role: 'Lead Infrastructure Eng',
    department: 'Engineering',
    lat: 46,
    lng: 53,
    carrier: 'Globe',
    normalSignalStrength: -75,
    battery: 88,
    status: 'Yellow',
    avatar: 'MS',
    address: 'Tres de Abril St., Labangon, Cebu City',
  },
  {
    id: 'emp-2',
    name: 'Jose Antonio Luna',
    role: 'Director of Operations',
    department: 'Operations',
    lat: 45,
    lng: 75,
    carrier: 'DITO',
    normalSignalStrength: -115,
    battery: 42,
    status: 'Red',
    avatar: 'AL',
    address: 'Corner P. Lopez & Borromeo St., Cebu City',
  },
  {
    id: 'emp-3',
    name: 'Mateo Rodriguez',
    role: 'SecOps Architect',
    department: 'Security',
    lat: 28,
    lng: 32,
    carrier: 'Smart',
    normalSignalStrength: -65,
    battery: 94,
    status: 'Green',
    safetyMessage: 'Evacuated the immediate vicinity, family is safe at the barangay hall.',
    avatar: 'MR',
    address: 'Gorordo Ave., Kamputhaw, Cebu City',
  },
  {
    id: 'emp-4',
    name: 'Dr. Ramon Magsaysay Jr.',
    role: 'HR Crisis Manager',
    department: 'People Operations',
    lat: 24,
    lng: 76,
    carrier: 'Smart',
    normalSignalStrength: -98,
    battery: 15,
    status: 'Yellow',
    avatar: 'RM',
    address: 'Salinas Dr., Lahug, Cebu City',
  },
  {
    id: 'emp-5',
    name: 'Corazon Aquino-Cruz',
    role: 'EHS Lead Representative',
    department: 'Safety & Compliance',
    lat: 64,
    lng: 24,
    carrier: 'Globe',
    normalSignalStrength: -105,
    battery: 61,
    status: 'Red',
    avatar: 'CA',
    address: 'Katipunan St., Tisa, Cebu City',
  },
  {
    id: 'emp-6',
    name: 'Lito "Lolong" Lapid',
    role: 'Field Rescue Coordinator',
    department: 'Operations',
    lat: 32,
    lng: 36,
    carrier: 'Globe',
    normalSignalStrength: -78,
    battery: 78,
    status: 'Green',
    safetyMessage: 'Active fire is down the block, structure secured, status clear.',
    avatar: 'LL',
    address: 'B. Rodriguez St., Sambag II, Cebu City',
  },
  {
    id: 'emp-7',
    name: 'Manny Pacquiao',
    role: 'Chief Security Specialist',
    department: 'Security',
    lat: 85,
    lng: 18,
    carrier: 'DITO',
    normalSignalStrength: -85,
    battery: 100,
    status: 'Green',
    safetyMessage: 'Assembled safely outside. Ready to cooperate on field assistance.',
    avatar: 'MP',
    address: 'SRP Coastal Highway Res., Talisay City',
  },
  {
    id: 'emp-8',
    name: 'Isagani G. Ilustre',
    role: 'Quality Assurance Lead',
    department: 'Engineering',
    lat: 27,
    lng: 80,
    carrier: 'Smart',
    normalSignalStrength: -95,
    battery: 98,
    status: 'Yellow',
    avatar: 'II',
    address: 'A.S. Fortuna St., Banilad, Cebu City',
  },
  {
    id: 'emp-9',
    name: 'Diego Silang',
    role: 'Cebu R&D Director',
    department: 'R&D',
    lat: 49,
    lng: 74,
    carrier: 'DITO',
    normalSignalStrength: -120,
    battery: 33,
    status: 'Red',
    avatar: 'DS',
    address: 'F. Llamas St., Punta Princesa, Cebu City',
  },
  {
    id: 'emp-10',
    name: 'Jane Go-Tan',
    role: 'Facilities Coordinator',
    department: 'Operations',
    lat: 66,
    lng: 21,
    carrier: 'Smart',
    normalSignalStrength: -70,
    battery: 82,
    status: 'Green',
    safetyMessage: 'Safely outside fire radius, monitoring building facilities.',
    avatar: 'JG',
    address: 'Talisay Proper, Cebu',
  },
  {
    id: 'emp-11',
    name: 'Kenneth Sy',
    role: 'Junior Software Engineer',
    department: 'Engineering',
    lat: 21,
    lng: 44,
    carrier: 'Smart',
    normalSignalStrength: -118,
    battery: 55,
    status: 'Red',
    avatar: 'KS',
    address: 'M.J. Cuenco Ave., Mabolo, Cebu City',
  },
  {
    id: 'emp-12',
    name: 'Joy Theresa Lim',
    role: 'Regional Finance Officer',
    department: 'Finance',
    lat: 31,
    lng: 33,
    carrier: 'Globe',
    normalSignalStrength: -80,
    battery: 91,
    status: 'Green',
    safetyMessage: 'Heard the sirens but completely out of harm’s way here.',
    avatar: 'JL',
    address: 'Geonzon St., Cebu IT Park, Cebu City',
  }
];

export const DISASTER_SCENARIOS: DisasterConfig[] = [
  {
    id: 'earthquake',
    name: 'M 6.8 Tectonic Earthquake',
    subName: 'Undersea Fault Line Shocks',
    icon: 'earthquake',
    color: 'red',
    colorClass: 'text-red-700 bg-red-50 border-red-200',
    hexColor: '#ef4444',
    defaultX: 52,
    defaultY: 48,
    defaultRadius: 25,
    locationName: 'Mactan Channel Tectonic Fault',
    description: 'A 6.8 magnitude shallow fracture causing tectonic block stress, structural building failures, and severe local cellular line congested bottlenecks.',
    greenTemplates: [
      'Evacuating area. Road blockages encountered but safe.',
      'Assisting neighbors. Cellular signals fluctuating.',
      'Power cut out. Safe in ground floor shelter.',
      'Rallied with rescue teams. Solid signal strength.',
      'Shaking was intense, but building structure intact.',
      'Safe at remote hub facility. Standing by for instructions.'
    ],
    replyTemplates: [
      'Safe. Sheltered at base depot with supplies.',
      'Disaster felt strongly. Safe. Device battery low.',
      'Working at emergency ward, structural integrity OK.',
      'Relocated north of epicenter. Signal coverage established.',
      'Visual safety matches. Awaiting emergency transport.',
      'Confirmed OK. Family gathered, safe.'
    ]
  },
  {
    id: 'typhoon',
    name: 'Super Typhoon "Odette II"',
    subName: 'Category 5 Cyclonic Wind Wall',
    icon: 'typhoon',
    color: 'cyan',
    colorClass: 'text-cyan-700 bg-cyan-50 border-cyan-200',
    hexColor: '#06b6d4',
    defaultX: 62,
    defaultY: 38,
    defaultRadius: 40,
    locationName: 'East Coast Typhoon Landfall',
    description: 'A massive Category 5 tropical typhoon sweeping Cebu with 215 km/h gusts, torrential rainfall floods, and storm surges disrupting key telecommunications nodes.',
    greenTemplates: [
      'Extreme wind gusts. Seeking solid concrete shelter.',
      'Heavy street flooding nearby. Moved upstairs and safe.',
      'Utility storm outages. Power down, family safe.',
      'Evacuated coastal sector. Gathered at storm shelter dome.',
      'Windows holds up well against winds. High water levels.',
      'Sheltering at Mactan storage bunker. Rations set, safe.'
    ],
    replyTemplates: [
      'Winds are tearing lines, but concrete walls holding safe!',
      'Relocated to higher office level. Floating debris outer streets.',
      'Safe at emergency evacuation school. Signal drops occasionally.',
      'Safe. Rain slowing down, conserving generator fuel.',
      'Barangay typhoon post reporting. Water receding, safe.',
      'Secure here. High cellular congestion, SMS working fine.'
    ]
  },
  {
    id: 'fire',
    name: 'Dense Residential Block Fire',
    subName: 'Barangay Fire Hazard Outbreak',
    icon: 'fire',
    color: 'orange',
    colorClass: 'text-orange-700 bg-orange-50 border-orange-200',
    hexColor: '#f97316',
    defaultX: 23,
    defaultY: 36,
    defaultRadius: 8,
    locationName: 'Cebu Commercial High-density Block',
    description: 'An intense, rapid, localized residential conflagration causing dangerous thermal plumes, thick carbon fumes, and utility wire power shutdowns.',
    greenTemplates: [
      'Thick black smoke clouds. Evacuated sector safely.',
      'Local power grid isolated for security. Standing by safe.',
      'Fire trucks actively clearing perimeter. All clear.',
      'Evacuated structure immediately. safe at compound.',
      'Assembled at barangay community oval. Secure and accounted.',
      'Safe. Fire controlled 4 houses away, moving to safety line.'
    ],
    replyTemplates: [
      'House cleared. Evacuated block to relative safe ground.',
      'Escape path clear. No injuries. Commencing safety reports.',
      'Safe at nearby commercial parking zone. Fire truck at scene.',
      'Safe. Smoke dissipating. Family sheltered at central oval.',
      'Fire wall contained. Safe in secondary barangay line.',
      'Cleared dense housing alley safely. In touch with marshals.'
    ]
  }
];

